// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/compute/ForwardingRule.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/samples/base_configs/query_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/querycheck"
	"github.com/hashicorp/terraform-plugin-testing/querycheck/queryfilter"
	"github.com/hashicorp/terraform-plugin-testing/tfversion"

	"github.com/hashicorp/terraform-provider-google/google/acctest"
	"github.com/hashicorp/terraform-provider-google/google/envvar"
	_ "github.com/hashicorp/terraform-provider-google/google/services/compute"
)

var (
	_ = strings.Trim
	_ = envvar.TestEnvVar
	_ = time.Now
)

func TestAccComputeForwardingRuleListQuery_generated(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)
	context := map[string]interface{}{
		"backend_name":         "tf-test-website-backend" + randomSuffix,
		"forwarding_rule_name": "tf-test-byoipv6-forwarding-rule" + randomSuffix,
		"ip_address":           fmt.Sprintf("2600:1901:4457:1:%d:%d::/96", acctest.RandIntRange(t, 0, 9999), acctest.RandIntRange(t, 0, 9999)),
		"ip_collection_url":    "projects/tf-static-byoip/regions/us-central1/publicDelegatedPrefixes/tf-test-forwarding-rule-mode-pdp",
		"network_name":         "tf-test-website-net" + randomSuffix,
		"region":               envvar.GetTestRegionFromEnv(),
		"project":              envvar.GetTestProjectFromEnv(),
		"random_suffix":        randomSuffix,
	}

	var listDisplayName acctest.ListDisplayName
	var listScope acctest.ListScopeCapture
	acctest.VcrTest(t, resource.TestCase{
		TerraformVersionChecks: []tfversion.TerraformVersionCheck{
			tfversion.SkipBelow(tfversion.Version1_14_0),
		},
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckComputeForwardingRuleDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeForwardingRule_forwardingRuleExternallbByoipv6Example(context),
				Check: resource.ComposeTestCheckFunc(
					listDisplayName.Capture(
						"google_compute_forwarding_rule.default",
						[]string{
							"name",
						},
					),
					listScope.Capture(map[string]string{}),
				),
			},
			{
				Query:           true,
				Config:          testAccComputeForwardingRule_forwardingRuleExternallbByoipv6ExampleListQuery(context),
				ConfigVariables: listScope.AsConfigVariables(),
				QueryResultChecks: []querycheck.QueryResultCheck{
					querycheck.ExpectLengthAtLeast("google_compute_forwarding_rule.list_query", 1),
					querycheck.ExpectResourceDisplayName(
						"google_compute_forwarding_rule.list_query",
						queryfilter.ByDisplayName(listDisplayName.CheckValue()),
						listDisplayName.CheckValue(),
					),
				},
			},
		},
	})
}

func testAccComputeForwardingRule_forwardingRuleExternallbByoipv6ExampleListQuery(context map[string]interface{}) string {
	return acctest.Nprintf(`
list "google_compute_forwarding_rule" "list_query" {
    provider = google
	limit = 10000
    config {
    }
}
`, context)
}
