// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import (
	"fmt"
)

func testAccComputeAddress_addressBasicExample(prefix string) string {
	return fmt.Sprintf(`
resource "google_compute_address" "default" {
  name = "address-%s"
}
`, prefix,
	)
}
func testAccComputeAddress_addressWithSubnetworkExample(prefix string) string {
	return fmt.Sprintf(`
resource "google_compute_network" "default" {
  name = "network-%s"
}

resource "google_compute_subnetwork" "default" {
  name          = "subnetwork-%s"
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-central1"
  network       = "${google_compute_network.default.self_link}"
}

resource "google_compute_address" "internal_with_subnet_and_address" {
  name         = "address-%s"
  subnetwork   = "${google_compute_subnetwork.default.self_link}"
  address_type = "INTERNAL"
  address      = "10.0.42.42"
  region       = "us-central1"
}
`, prefix, prefix, prefix,
	)
}
